name: Test Monitoring Plugin

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: update apt repositories
      run: sudo apt-get -qq update
    - name: install required packages
      run: sudo apt-get install -y sshpass jq cpanminus libwww-perl liblwp-protocol-https-perl libjson-perl strace
    - name: install Monitoring::Plugin
      run: sudo cpanm Monitoring::Plugin
    - name: clone bats-core
      run: git clone https://github.com/bats-core/bats-core.git bats-core                                                                            
    - name: pre pull netscalercpx image
      run: docker pull store/citrix/netscalercpx:${CONTAINER_VERSION:-12.0-56.20}
    - name: pre pull nginx image
      run: docker pull nginx:${NGINX_CONTAINER_VERSION:-latest}
    - name: start netscaler cpx
      run: docker run -e EULA=yes -dt -p 22 -p 80 -p 161/udp --ulimit core=-1 --cap-add=NET_ADMIN --name netscalercpx store/citrix/netscalercpx:${CONTAINER_VERSION:-12.0-56.20}
    - name: start web01 container
      run: docker run -dt -p 80 --name web1 nginx:${NGINX_CONTAINER_VERSION:-latest}
    - name: start web02 container
      run: docker run -dt -p 80 --name web2 nginx:${NGINX_CONTAINER_VERSION:-latest}

    - name: get netscaler ip
      run: export NETSCALER_IP=$(docker inspect netscalercpx | jq -r .[0].NetworkSettings.IPAddress)
    - name: get web01 ip
      run: export WEB01_IP=$(docker inspect web01 | jq -r .[0].NetworkSettings.IPAddress)
    - name: get web02 ip
      run: export WEB02_IP=$(docker inspect web02 | jq -r .[0].NetworkSettings.IPAddress)
    - name: replace web01 ip in ns.conf
      run: sed -i "s/WEB01_IP/${WEB01_IP}/g" tests/ns.conf
    - name: replace web02 ip in ns.conf
      run: sed -i "s/WEB02_IP/${WEB02_IP}/g" tests/ns.conf

    - name: configure netscaler
      run: tests/travis_prepare.sh

    - name: run tests via bats
      run: bats-core/bin/bats tests/bats
