name: CI Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: show containers
      run: docker ps -a

    - name: install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y sshpass jq cpanminus libwww-perl liblwp-protocol-https-perl libjson-perl strace
        sudo cpanm Monitoring::Plugin
        git clone https://github.com/bats-core/bats-core.git bats-core

    - name: prepull docker images
      run: |
        docker pull store/citrix/netscalercpx:${CONTAINER_VERSION:-12.0-56.20}
        docker pull nginx:${NGINX_CONTAINER_VERSION:-latest}

    - name: start required containers
      run: |
        docker run -e EULA=yes -dt -p 22 -p 80 -p 161/udp --ulimit core=-1 --cap-add=NET_ADMIN --label name=netscalercpx --name netscalercpx store/citrix/netscalercpx:${CONTAINER_VERSION:-12.0-56.20}
        docker run -dt -p 80 --label name=web01 --name web01 nginx:${NGINX_CONTAINER_VERSION:-latest}
        docker run -dt -p 80 --label name=web02 --name web02 nginx:${NGINX_CONTAINER_VERSION:-latest}
        sleep 30

    - name: prepare ns.conf
      run: |
        export NETSCALER_ID=$(docker ps -a --filter label=name=netscalercpx -q)
        export WEB01_ID=$(docker ps -a --filter label=name=web01 -q)
        export WEB02_ID=$(docker ps -a --filter label=name=web02 -q)
        export NETSCALER_IP=$(docker inspect ${NETSCALER_ID} | jq -r .[0].NetworkSettings.IPAddress)
        export WEB01_IP=$(docker inspect ${WEB01_ID} | jq -r .[0].NetworkSettings.IPAddress)
        export WEB02_IP=$(docker inspect ${WEB02_ID} | jq -r .[0].NetworkSettings.IPAddress)
        sed -i "s/WEB01_IP/${WEB01_IP}/g" tests/ns.conf
        sed -i "s/WEB02_IP/${WEB02_IP}/g" tests/ns.conf
        echo "::set-env name=NETSCALER_IP::${NETSCALER_IP}"

    - name: configure netscaler
      run: tests/travis_prepare.sh

    - name: run tests via bats
      run: |
        bats-core/bin/bats tests/bats
